language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/client-secret.json"
  global:
  - secure: U878Y54AwtoIZI9QwKtTNNsNPPhiCHWaUk/ZVNm9y4HeRdhHOAZ7CfkzArCtwfm06BNTBTW2Jd1+yTM8g2ZSX9dcL28ROtvHzrF09p04xMpgapSWW8/xVVMDMMtrlQUWQG+hlygmzzVDdz3dmcX9nYw7nOUBKXZiwsHpoRPLhZj8AnUFODYQOfAiI9g9JnV25hA4BkH2PccecF4KOtoE0RmamwJojZeJG0RfuM2PtBT528d/K0raf42cYX+mCLDT3/BixX4ajk2E4xgeJtlt7kCjgCKX17hz1SqXl5Dyg0p67ZCQ6VIQz0mJuSEy4q0Gya22fj7ciqwtb8vJmfFPlHs5v5TitjG/sOIqrQ3bbtJZGmMOucm6IrctIQmuBAL4ziAcPPMhKpQD9S4wx2ln02WcSRLIIvgpHackuJdeu/QaxRcPDegZCKU/MP6aZqJxG5b57FV/KLwtaU0q7dM5RItchifYvrb9AtScbnJ2BXOYKZZwNsR8nbeovyLRFHVTQCUySYe2K1n+TGOxPVGwFZAAZimJSpFNVl87k8KH3lzqiVXcUrQYs3JYdFBAWEKNK7+IjWthR8zBKt0iMabO8ISqBFxXh49+Ied/gD5Zda6PPT0He2/mES9irYCZYH7MjsC5AzimdaWPk2diI1Imaqjphu6nmxjifukM14CbfqQ=
  - secure: pCxCM8Z1SWJShbkwBg6vd5tYtCLFZ+NHgjbPMqur2ugTJ7fCwGLXd4IO+mxDM8IyNFDqptKWceAFoZb2wu50Z/MagnRk1VBfoGZATchfVKU1xRnXRT1iSzb6uxyjttu1dsO5zJgMG4JB1IwoLrt8rQrOB54e5CKYQSM9u0plaxo64n10Oy0axGbvGjF6w1q4QwwVghfgGFIEEB7AtW57d4rle60apCgE4XI91a+epIShxFv8drNZ3vsC28cCw2myEqNpLep1hry9A/g+Yg2PDvghzYSC9W8cpld97Yezxd5fG7Jv2B8np5uhsGEPRY7q9z8kuh2CjehZUZwOb8Q7s5jNAlymf7HRuceBPvmVrP/OzExmeuQY6xQlPEobes9dpQ1mhJLsRmHQ7meD8xE/mTkDJSsb+6ZZXkNl8xCioaCkuK/Bnohx1vjkcwBUJRjSMFzqAJbGtkV+seCRKa+xq/1L+0P9yc8sTcykeGVgWzLHww3AUt40dyDyNczNviBdF5qLoTwTPdx5nL9xzqz4Z5DH138npqj3XQUdn2jt2T+G3j83+Y/j0iA/gtyYt1RFmsbtMNrYCNOhlhjNFz4/maBYgsLDTUFD+Za7ZFJBco5321m0Sv2OSKSgRUsrfVy0rOOqD39UtUHk6pqZxc4VSkPHfxlj3ZHWj5SxVcZNJfU=
  - secure: b63jjDSQMTUseugXWPS8tm8lu3IUnQGWMu0PPhqmXCqUVvo6DbOt/CqYB3E1CtQFR8sRXMqIAFfeOTKqcTVMJ5Mc6g+7PCljV9LN8rNxo8yceHytQAFtucdCHeZ9dVdzb5dUD4Sq0aR+sHJ9HTAptTOQs5wHoAvpjIE0MFZzh1sV5zgBeOTF2AV0Hso2dOy1QPVAnX0i4mZuEJuD+s5RV79eBpW9Ma88nA2OEEnA5VlBjw16EyBai9mLwmu2YK4NzksqGxbiMgP/7/5eDypBkIRZTiHshOkmpN/VksSssJ6CK5lm78KRHkT+eWF/nGK4c2zWIRki+3a5lTfZjizdxGyxUkzolIkzVjGeVDSaHGKe9RmFawaWrYgVxTGr6tRpoefeBsMuvfGa2oesL/0aWvu5SLDmXIrT23T3Lqylsm5PHYEysxRPdWnZksdf3fKu/dM9sBwBBGREWXN26gRQ9/Wrb5MO2N71xKIEX+BGExhhLU3m4Ajn888mm4Ed5osBysVeirJLTeTmcy4RoM3iE6eKYI47F7kffkTdg8szU5zD74Ohl4PQpAWTiNWQcMO7gWkDBYVllXpMGvJ4SeDqnkRnWLkeKaZnJvE3HI0YE4ffVgzSBVZUhKtOxsg83JHVtOmFjVvLUuKOySUp8wUG0nLBgOiLoqOHUN6tN9OmBp0=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_c39ba742377e_key -iv $encrypted_c39ba742377e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
