language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: EA15t4VpaAbgDqTLknVyD8fCcKHj6L3InobC1e3zJkn0gkKpi8Yll5fwaPd+pgGZVOsPxnmphapJ7o/7P0OhGIZx4XQSQGhQRtuTpEPQ7EQ4IvaXytQJCtRO5VGKO/mr0urwjn866C0uYeLMSyUBpaDA1zXaxM1rUbH85X+KNmnUXQ62K5+zY52CyPpgqhRgDtDoisotr0FmUFOUDLcfF9JhUrZ96+nREQ5kwOmeXrBIq3W/eOGk7InsLgzzoYWu6abIthSHFfV5LvzQbAmn3gIRz1ithjsqg5WmxOJphHe2klfT0J1alWfGPYYO60fZZgTxonYXAA2DOyLiyabZRK8Etw/d4Cyg30fkbUNV3mJWjUKJnmV45b+lU9uDI60Q0VqVy/byvRuU5/pwrvN8Af5fCkGS2CoqpTTJ14TNGmGZzeafwTXSHtPZYR9fGf9vhCm6jm64WUBQpNMInKlCOq5CL+xcv0DOdmkHF3ogBP8LFFS5mnRLNIAJT9uuChPrn3azfH1ywyqMasfmFjMWLCs/zqafgM/Rr42blhhV61nOB418Akicv7YV1l5OodnHVYKbM3DTDyBuj+/dcUNs2hNiaViGuhY7EYWkT+Zx7kDpL8Wg+qz2nVgqdo3FMLpM8Hlr2NnrU+a6FHM/CEr4dJcCvnINIIxJsPe/eOC6J5E=
  - secure: cpmFDT1HM0Wu+xeMMFpTm8zwZkELZ3SeJBszmR03qVljP4+VmyuCvfhs0bxpNhZ81mbGgonThe67EfzLWwlq459T9vjsfbymc/HiI3XzcRv+9QRMHgDko6mZ2yO82wBTA0M8l51Y0YxfJSxsNGvxCIlfjcf8mW2SRBLFs9RaNrmRYnfJBvSwIvRL0OP2IVYYpBLh8w4OPIhD0ApCydnrVx7H5GEkcgx0VothqSGEZe9xgsCZltRNN08Lb+7PvKqdsOsO/aTICoCyT3ykCetWReYiXmv+ZoscuKSoTpfEccAUm2oDIacEjh2lQf97/qTu6SMAkKRs9f5+f+L8vMWvCCZvr00V2+i3beuhm9eHX1ZIDi/wtniYZwvVU1jxlCS4tlPZgDCZ+XAiVPGyh7MgTcwEC2SMk6uLn2JU5IpI+ZbY1Pu2ssDJvCEszI6zShxeGLpXl2FIoUDzg8Ka0jutFg1TiisiMqjXtfsqWN3cGv9L92vSPIGFionwrjdRxMVZ4x00c8vVbdO+W2dBBgreXXmu9oK4tzl7GmobeA52E+qn9m3IxieGVFgQn5sOGe42v5QDsx0Is7XWukYN4djYehb2convvYWSrXt7G9VpPw9A1ZaPSoQ4xecypJoUZ4KnRJbAJS1pAorNyR7YedCt78qc7i51R72tzhE4Rk6qqB4=
  - secure: eboJ9ZvfL8QAcEIRieI/swix+0a3WUJMw3kUpnyTXFA7Wdqv+/QchICkmanuYwD+oCpvB2nrEo7u9U/DYgeYmg+gQuzZxdSGNSwWkAuZbynS8mfvUSjaOkx4JT9xnRJaC9N7JVXrBcdUxyCsOETLEVeo62h5x2cpOXATp6gcDJ5JSK3bgpaOsW5jKwIT1wj5n/dbkRznRJ+GYQjlhPUE6EDn6n4QjCJdC+EnIBQUojA9MyG+PUJXUosPuHmsF/pjSk8yi55nMFtxIQoTzpmrbIF2LLWALFxO2R7xFMCl4bERTSc3P112pfNpIyV4nStMA6XogC7zGRzLE55Sl3YH9bfnLPfB5QPDMTFv88d2Jmk9AY5RE9Qm4qYZvwZedPFnyzOjfSLBJfQ4PF0j2V6S0ZIbG2cb5l7WhFXQhF01QNYEGZ1Dsf1whpip/8Qn0K6+i5DymEC+JsO94wpDTqpwkk7IpsbsFqWdj0mODcxIZ1cBfU10eGUXqvwmM3uCmUN11hmWRyTNgwgYQhSu1lHoKFLIRR/S9NJIvn4KZi6Ef1hACCpbkSPtygqYHozUmAQHcYIYVLIKpXEPAYeBapbpPdDEv9qJPElre/it1jSFnQ0qJbhHOlSajTKGuYQLVF3AfQHLZJBR6weGtMDDtkiyxhKrk1Tz0eNQKDC5CeFGBbA=
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_c39ba742377e_key -iv $encrypted_c39ba742377e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
