language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: EA15t4VpaAbgDqTLknVyD8fCcKHj6L3InobC1e3zJkn0gkKpi8Yll5fwaPd+pgGZVOsPxnmphapJ7o/7P0OhGIZx4XQSQGhQRtuTpEPQ7EQ4IvaXytQJCtRO5VGKO/mr0urwjn866C0uYeLMSyUBpaDA1zXaxM1rUbH85X+KNmnUXQ62K5+zY52CyPpgqhRgDtDoisotr0FmUFOUDLcfF9JhUrZ96+nREQ5kwOmeXrBIq3W/eOGk7InsLgzzoYWu6abIthSHFfV5LvzQbAmn3gIRz1ithjsqg5WmxOJphHe2klfT0J1alWfGPYYO60fZZgTxonYXAA2DOyLiyabZRK8Etw/d4Cyg30fkbUNV3mJWjUKJnmV45b+lU9uDI60Q0VqVy/byvRuU5/pwrvN8Af5fCkGS2CoqpTTJ14TNGmGZzeafwTXSHtPZYR9fGf9vhCm6jm64WUBQpNMInKlCOq5CL+xcv0DOdmkHF3ogBP8LFFS5mnRLNIAJT9uuChPrn3azfH1ywyqMasfmFjMWLCs/zqafgM/Rr42blhhV61nOB418Akicv7YV1l5OodnHVYKbM3DTDyBuj+/dcUNs2hNiaViGuhY7EYWkT+Zx7kDpL8Wg+qz2nVgqdo3FMLpM8Hlr2NnrU+a6FHM/CEr4dJcCvnINIIxJsPe/eOC6J5E=
  - secure: eboJ9ZvfL8QAcEIRieI/swix+0a3WUJMw3kUpnyTXFA7Wdqv+/QchICkmanuYwD+oCpvB2nrEo7u9U/DYgeYmg+gQuzZxdSGNSwWkAuZbynS8mfvUSjaOkx4JT9xnRJaC9N7JVXrBcdUxyCsOETLEVeo62h5x2cpOXATp6gcDJ5JSK3bgpaOsW5jKwIT1wj5n/dbkRznRJ+GYQjlhPUE6EDn6n4QjCJdC+EnIBQUojA9MyG+PUJXUosPuHmsF/pjSk8yi55nMFtxIQoTzpmrbIF2LLWALFxO2R7xFMCl4bERTSc3P112pfNpIyV4nStMA6XogC7zGRzLE55Sl3YH9bfnLPfB5QPDMTFv88d2Jmk9AY5RE9Qm4qYZvwZedPFnyzOjfSLBJfQ4PF0j2V6S0ZIbG2cb5l7WhFXQhF01QNYEGZ1Dsf1whpip/8Qn0K6+i5DymEC+JsO94wpDTqpwkk7IpsbsFqWdj0mODcxIZ1cBfU10eGUXqvwmM3uCmUN11hmWRyTNgwgYQhSu1lHoKFLIRR/S9NJIvn4KZi6Ef1hACCpbkSPtygqYHozUmAQHcYIYVLIKpXEPAYeBapbpPdDEv9qJPElre/it1jSFnQ0qJbhHOlSajTKGuYQLVF3AfQHLZJBR6weGtMDDtkiyxhKrk1Tz0eNQKDC5CeFGBbA=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_c39ba742377e_key -iv $encrypted_c39ba742377e_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: s78ib/yjBxKys6YNyMprqSR9GpAvvWZvvRAMePe9XF6Wh5HZYJdaxL5C340w8olL3PDILteKttnzkVFL0GT/P04Mo2owJtU4fbXQAvelnQtX3q4Xefv4uCEgc0oemQJXdtUsHJ0y6i0Vvg0Ksz3riy19yjnDXaliIjPU+1F4htXal6/WaSgL8ui1bDWKVFURhPba+nTwLSgWutb64qWxPdKZxroyBaZfWhDr6Im4A3ifrmrWQ+Kdff4aiIqZHmTKPVM36sDjJad5hbl/6Jga7oBOQvgHyQMfuZYdLwAg/k9/WBYIdc5FlV7iHiCF8Nx5M6b1wjvbSQP25QjsulHAZLaY28RBaUO7Rok22QmzlPe0MlT+7BaZcvQTjRcCrA99MMgbm0+m2EFi+J/yd/4uO/T03432cBeq4DSjopfwRd3qpUxKgUxBr0EPu5NRGfgAHV5w5D1vOHdJROw/yR7wyy2L6bHZj8TVhKMeZ/0Snl+SfCPmkzbFKzCBH1DcGsyGISsWbwvUpIRt9Ivz8ugNtqHwr3nVNEa6pkFc61ajNMhA9C7pwqIyItIkjhYJ0N129E+Gw+AD0cEQ1vyjWubi+yIytXU+4bvy8it0eJ5ZgxKlo+gYD+vxBTEo5Yle/P8+Q1iPtnoXzDkchnBo2wltbmAQ7xjhgr7OYyVXJvd5UpQ=
