language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_c39ba742377e_key -iv $encrypted_c39ba742377e_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar xvf credentials.tar.gz
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash;
  fi
#- mv google_compute_engine /home/travis/.ssh/
- gcloud auth activate-service-account --key-file client-secret.json
- chmod 0600 /home/travis/.ssh/google_compute_engine
